project_id = "p98pqg"

[functions.chat-agent]
verify_jwt = false

[functions.generate-reading-insights]
verify_jwt = false

[functions.chat-infografico]
verify_jwt = false

[functions.generate-content]
verify_jwt = false

[functions.generate-slides-content]
verify_jwt = false

[functions.resumir-contrato]
verify_jwt = false

[functions.explain-chart]
verify_jwt = false

[functions.generate-assistant-suggestions]
verify_jwt = false

[functions.generate-chat-image]
verify_jwt = false

[functions.generate-recommendations]
verify_jwt = false

[functions.notify-similar-promotions]
verify_jwt = false

[functions.ebook-reading-agent]
verify_jwt = false

[functions.generate-reading-questions]
verify_jwt = false

[functions.transcribe-audio]
verify_jwt = false
