project_id = "p98pqg"

[functions.chat-agent]
verify_jwt = false

[functions.generate-reading-insights]
verify_jwt = false

[functions.chat-infografico]
verify_jwt = false

[functions.generate-content]
verify_jwt = false

[functions.generate-slides-content]
verify_jwt = false

[functions.resumir-contrato]
verify_jwt = false

